package com.airmanbzh.euler;

import com.sun.org.glassfish.gmbal.Description;

public class Project {

    @Description("If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9." +
            "The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000")
    public static Integer exOne(Integer n) {
        Integer sum = 0;

        if (n > 0) {
            for (Integer i = 0; i < n; i++) {
                if (i % 3 == 0 || i % 5 == 0) {
                    sum += i;
                }
            }
        }

        return sum;
    }

    @Description("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n" +
            "\n" +
            "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n" +
            "\n" +
            "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.")
    public static Integer exTwo(Integer max) {
        Integer sum = 0;
        Integer lastPrev = 0;
        Integer prev = 1;
        Integer currentValue = 1;
        Integer i = 0;

        while (currentValue <= max) {
            if (currentValue % 2 == 0) {
                sum += currentValue;
            }

            currentValue = lastPrev + prev;

            lastPrev = prev;
            prev = currentValue;

            i++;
        }

        return sum;
    }
}
